# Supported Funding Model Platforms

- **GitHub Sponsors**: [user1, user2, user3, user4]  
  *(Replace with up to 4 GitHub Sponsors-enabled usernames)*

- **Patreon**: patreon_username  
  *(Replace with a single Patreon username)*

- **Open Collective**: open_collective_username  
  *(Replace with a single Open Collective username)*

- **Ko-fi**: ko_fi_username  
  *(Replace with a single Ko-fi username)*

- **Tidelift**: tidelift_platform/package-name  
  *(Replace with a single Tidelift platform-name/package-name, e.g., npm/babel)*

- **Community Bridge**: community_bridge_project_name  
  *(Replace with a single Community Bridge project-name, e.g., cloud-foundry)*

- **Liberapay**: liberapay_username  
  *(Replace with a single Liberapay username)*

- **IssueHunt**: issuehunt_username  
  *(Replace with a single IssueHunt username)*

- **LFX Crowdfunding**: lfx_crowdfunding_project_name  
  *(Replace with a single LFX Crowdfunding project-name, e.g., cloud-foundry)*

- **Polar**: polar_username  
  *(Replace with a single Polar username)*

- **Buy Me a Coffee**: buy_me_a_coffee_username  
  *(Replace with a single Buy Me a Coffee username)*

- **Thanks.dev**: thanks_dev_username  
  *(Replace with a single thanks.dev username)*

- **Custom URLs**: ['link1', 'link2', 'link3', 'link4']  
  *(Replace with up to 4 custom sponsorship URLs)*
